# UN Comtrade HS 코드 데이터베이스
# 출처: Harmonized System (HS) 2022 기준
# 형식: "한글명 (English name)"

# HS 2자리 챕터 (97개)
HS2_CODES = {
    "01": "산동물 (Live animals)",
    "02": "육류·식용 설육 (Meat and edible meat offal)",
    "03": "어류·갑각류·연체동물 (Fish, crustaceans, molluscs)",
    "04": "낙농품·조란·천연꿀 (Dairy produce, eggs, honey)",
    "05": "기타 동물성 생산품 (Other animal products)",
    "06": "산 수목·기타 식물 (Live trees and other plants)",
    "07": "채소·뿌리·괴경 (Edible vegetables, roots, tubers)",
    "08": "식용 과실·견과류 (Edible fruit and nuts)",
    "09": "커피·차·마테·향신료 (Coffee, tea, maté, spices)",
    "10": "곡물 (Cereals)",
    "11": "제분공업·맥아·전분 (Milling industry products, starch)",
    "12": "채유용 종자·공업용 식물 (Oil seeds, industrial plants)",
    "13": "락·수지·식물성 수액 (Lac, gums, resins, vegetable saps)",
    "14": "식물성 편조물·기타 식물성 생산품 (Vegetable plaiting materials)",
    "15": "동식물성 유지·왁스 (Animal or vegetable fats and oils)",
    "16": "육류·어류 조제품 (Preparations of meat, fish)",
    "17": "당류·설탕과자 (Sugars and sugar confectionery)",
    "18": "코코아·코코아 조제품 (Cocoa and cocoa preparations)",
    "19": "곡물·곡분 조제품·빵류 (Preparations of cereals, flour, bread)",
    "20": "채소·과실 조제품 (Preparations of vegetables, fruit)",
    "21": "각종 조제 식료품 (Miscellaneous edible preparations)",
    "22": "음료·주류·식초 (Beverages, spirits, vinegar)",
    "23": "식품 공업 잔재·사료 (Residues from food industries, animal feed)",
    "24": "담배·담배 대용물 (Tobacco and tobacco substitutes)",
    "25": "소금·황·토석·석고·석회·시멘트 (Salt, sulphur, earth, stone, cement)",
    "26": "광석·슬래그·회분 (Ores, slag, ash)",
    "27": "광물성 연료·석유·광물성 왁스 (Mineral fuels, oils, waxes)",
    "28": "무기화학품·귀금속화합물 (Inorganic chemicals, precious metal compounds)",
    "29": "유기화학품 (Organic chemicals)",
    "30": "의약품 (Pharmaceutical products)",
    "31": "비료 (Fertilisers)",
    "32": "유기염료·페인트·잉크 (Dyes, paints, varnishes, inks)",
    "33": "정유·향수·화장품 (Essential oils, perfumes, cosmetics)",
    "34": "비누·세정제·윤활제·왁스·광택제 (Soap, detergents, lubricants, waxes)",
    "35": "단백질계 물질·전분풀·효소 (Albuminoidal substances, starches, enzymes)",
    "36": "화약·성냥·불꽃·화공품 (Explosives, matches, pyrotechnic products)",
    "37": "사진용 재료 (Photographic goods)",
    "38": "각종 화학공업 생산품 (Miscellaneous chemical products)",
    "39": "플라스틱과 그 제품 (Plastics and articles thereof)",
    "40": "고무와 그 제품 (Rubber and articles thereof)",
    "41": "원피·가죽 (Raw hides, skins, leather)",
    "42": "가죽제품·여행용품·핸드백 (Articles of leather, travel goods, handbags)",
    "43": "모피·모피제품 (Furskins and artificial fur)",
    "44": "목재·목탄·목제품 (Wood, charcoal, articles of wood)",
    "45": "코르크와 그 제품 (Cork and articles of cork)",
    "46": "짚·에스파르토·기타 편조물 (Manufactures of straw, esparto)",
    "47": "목재 펄프·종이 회수물 (Pulp of wood, recovered paper)",
    "48": "종이·판지·제지공업 제품 (Paper, paperboard, articles thereof)",
    "49": "인쇄서적·신문·그림·기타 인쇄물 (Printed books, newspapers, pictures)",
    "50": "견 (Silk)",
    "51": "양모·동물의 털 (Wool, fine or coarse animal hair)",
    "52": "면 (Cotton)",
    "53": "기타 식물성 방직용 섬유·지사 (Other vegetable textile fibres, paper yarn)",
    "54": "인조필라멘트·테이프 (Man-made filaments, strips)",
    "55": "인조스테이플섬유 (Man-made staple fibres)",
    "56": "워딩·펠트·부직포·특수사 (Wadding, felt, nonwovens, special yarns)",
    "57": "양탄자·기타 방직용 섬유 바닥깔개 (Carpets and other textile floor coverings)",
    "58": "특수 직물·술 달린 직물·레이스 (Special woven fabrics, tufted textile fabrics, lace)",
    "59": "침투·도포·피복된 방직용 섬유 (Impregnated, coated, covered textile fabrics)",
    "60": "편물 (Knitted or crocheted fabrics)",
    "61": "편물제 의류·의류부속품 (Articles of apparel, knitted or crocheted)",
    "62": "편물 외의 의류·의류부속품 (Articles of apparel, not knitted)",
    "63": "기타 방직용 섬유 제품 (Other made-up textile articles)",
    "64": "신발류 (Footwear)",
    "65": "모자류 (Headgear)",
    "66": "산·지팡이·좌석용 스틱·채찍류 (Umbrellas, sun umbrellas, walking sticks)",
    "67": "조제 깃털·깃털 제품·조화·인모 제품 (Prepared feathers, artificial flowers, human hair)",
    "68": "석·플래스터·시멘트·석면·운모 제품 (Articles of stone, plaster, cement, asbestos, mica)",
    "69": "도자제품 (Ceramic products)",
    "70": "유리와 그 제품 (Glass and glassware)",
    "71": "천연진주·귀석·귀금속·모조보석류 (Natural pearls, precious stones, precious metals)",
    "72": "철강 (Iron and steel)",
    "73": "철강제품 (Articles of iron or steel)",
    "74": "구리와 그 제품 (Copper and articles thereof)",
    "75": "니켈과 그 제품 (Nickel and articles thereof)",
    "76": "알루미늄과 그 제품 (Aluminium and articles thereof)",
    "77": "(예비 챕터 / Reserved)",
    "78": "납과 그 제품 (Lead and articles thereof)",
    "79": "아연과 그 제품 (Zinc and articles thereof)",
    "80": "주석과 그 제품 (Tin and articles thereof)",
    "81": "기타 비금속·서멧·그 제품 (Other base metals, cermets, articles thereof)",
    "82": "비금속제 공구·도구·칼붙이 (Tools, implements, cutlery of base metal)",
    "83": "비금속제 잡제품 (Miscellaneous articles of base metal)",
    "84": "원자로·보일러·기계류 (Nuclear reactors, boilers, machinery)",
    "85": "전기기기·음향·영상기기 (Electrical machinery, sound recorders, TV sets)",
    "86": "철도용 기관차·차량·선로용 설비 (Railway or tramway locomotives, rolling stock)",
    "87": "철도·전차 외의 차량 (Vehicles other than railway, tramway rolling stock)",
    "88": "항공기·우주선 (Aircraft, spacecraft)",
    "89": "선박과 수상 구조물 (Ships, boats, floating structures)",
    "90": "광학기기·사진기·의료용 기기 (Optical, photographic, cinematographic, medical instruments)",
    "91": "시계 (Clocks and watches)",
    "92": "악기 (Musical instruments)",
    "93": "무기·탄약 (Arms and ammunition)",
    "94": "가구·침구·조명기기·조립식 건물 (Furniture, bedding, lamps, prefabricated buildings)",
    "95": "완구·게임용구·운동용품 (Toys, games, sports requisites)",
    "96": "잡제품 (Miscellaneous manufactured articles)",
    "97": "예술품·수집품·골동품 (Works of art, collectors pieces, antiques)",
}

# HS 4자리 헤딩 (주요 품목 — 농축수산물 전체 + 주요 공산품)
HS4_CODES = {
    # 제1부: 산동물·동물성 생산품 (01~05장)
    "0101": "말·당나귀·노새 산 것 (Horses, asses, mules, live)",
    "0102": "소 산 것 (Bovine animals, live)",
    "0103": "돼지 산 것 (Swine, live)",
    "0104": "양·염소 산 것 (Sheep and goats, live)",
    "0105": "가금류 산 것 (Poultry, live)",
    "0106": "기타 산 동물 (Other live animals)",
    "0201": "쇠고기 냉장 (Meat of bovine animals, fresh or chilled)",
    "0202": "쇠고기 냉동 (Meat of bovine animals, frozen)",
    "0203": "돼지고기 신선·냉장·냉동 (Meat of swine, fresh, chilled or frozen)",
    "0204": "양·염소고기 신선·냉장·냉동 (Meat of sheep or goats, fresh, chilled or frozen)",
    "0205": "말·당나귀 고기 신선·냉장·냉동 (Meat of horses, asses, mules)",
    "0206": "소·돼지·양·염소 등 식용 설육 (Edible offal of bovine, swine, sheep)",
    "0207": "가금류 고기·식용 설육 (Meat and edible offal of poultry)",
    "0208": "기타 육류 신선·냉장·냉동 (Other meat, fresh, chilled or frozen)",
    "0209": "돼지지방·가금류 지방 (Pig fat, poultry fat)",
    "0210": "육류·식용 설육 염장·건조·훈제 (Meat and offal, salted, dried or smoked)",
    "0301": "산 어류 (Live fish)",
    "0302": "신선·냉장 어류 (Fish, fresh or chilled)",
    "0303": "냉동 어류 (Fish, frozen)",
    "0304": "어류 필레·어육 (Fish fillets and other fish meat)",
    "0305": "건조·염장·훈제 어류 (Fish, dried, salted or smoked)",
    "0306": "갑각류 (Crustaceans)",
    "0307": "연체동물 (Molluscs)",
    "0308": "수생 무척추동물 (Aquatic invertebrates other than crustaceans/molluscs)",
    "0401": "우유·크림 (Milk and cream, not concentrated/sweetened)",
    "0402": "농축·가당 우유·크림 (Milk and cream, concentrated or sweetened)",
    "0403": "버터밀크·요구르트·크림 (Buttermilk, yogurt, kephir)",
    "0404": "유청·변성 유제품 (Whey, modified milk products)",
    "0405": "버터·유지방 (Butter and other fats from milk)",
    "0406": "치즈·커드 (Cheese and curd)",
    "0407": "조란 (Birds eggs, in shell)",
    "0408": "조란 (껍데기 제거) (Birds eggs, not in shell)",
    "0409": "천연꿀 (Natural honey)",
    "0410": "동물성 식용 생산품 (Insect and other edible animal products)",
    "0501": "인모·돼지·멧돼지털·오소리털 (Human hair, pig/badger hair)",
    "0502": "돼지·멧돼지털 조제품 (Pigs, hogs, boars bristles)",
    "0504": "동물의 내장·방광·위 (Guts, bladders, stomachs of animals)",
    "0505": "깃털·솜털 (Skins/feathers of birds)",
    "0506": "뼈·뿔심·기타 (Bones, horn-cores)",
    "0507": "상아·거북등껍데기·고래수염 (Ivory, tortoise-shell, whalebone)",
    "0508": "산호·조가비·갑각류 껍데기 (Coral, shells, cuttlebone)",
    "0510": "용연향·해리향·영묘향·사향 (Ambergris, castoreum, civet, musk)",
    "0511": "기타 동물성 생산품 (Animal products n.e.s.)",
    # 제2부: 식물성 생산품 (06~14장)
    "0601": "구근·괴경·인경·구경·근경류 (Bulbs, tubers, corms, crowns, rhizomes)",
    "0602": "기타 산 식물 (Other live plants)",
    "0603": "절화·절화용 봉오리 (Cut flowers and flower buds)",
    "0604": "잎사귀·가지·기타 식물 부분 (Foliage, branches and other plant parts)",
    "0701": "신선·냉장 감자 (Potatoes, fresh or chilled)",
    "0702": "신선·냉장 토마토 (Tomatoes, fresh or chilled)",
    "0703": "양파·마늘·부추 (Onions, shallots, garlic, leeks)",
    "0704": "양배추·꽃양배추·브로콜리 (Cabbages, cauliflowers, broccoli)",
    "0705": "상추·치커리 (Lettuce and chicory)",
    "0706": "당근·순무·비트·셀러리액 (Carrots, turnips, beetroot, celeriac)",
    "0707": "오이·거킨 (Cucumbers and gherkins)",
    "0708": "꼬투리 채소 (Leguminous vegetables)",
    "0709": "기타 채소 신선·냉장 (Other vegetables, fresh or chilled)",
    "0710": "냉동 채소 (Vegetables, frozen)",
    "0711": "일시 저장 채소 (Vegetables provisionally preserved)",
    "0712": "건조 채소 (Dried vegetables)",
    "0713": "건조 두류 (Dried leguminous vegetables)",
    "0714": "카사바·칡·감자·참마 (Cassava, arrowroot, yams, sweet potatoes)",
    "0801": "코코넛·브라질너트·캐슈너트 (Coconuts, Brazil nuts, cashew nuts)",
    "0802": "기타 견과류 (Other nuts)",
    "0803": "바나나·플랜틴 (Bananas and plantains)",
    "0804": "대추야자·무화과·파인애플·아보카도 (Dates, figs, pineapples, avocados)",
    "0805": "감귤류 (Citrus fruit)",
    "0806": "포도 (Grapes)",
    "0807": "멜론·수박·파파야 (Melons, watermelons, papayas)",
    "0808": "사과·배·마르멜로 (Apples, pears and quinces)",
    "0809": "살구·체리·복숭아·자두 (Apricots, cherries, peaches, plums)",
    "0810": "기타 신선 과실 (Other fruit, fresh)",
    "0811": "냉동 과실 (Fruit, frozen)",
    "0812": "일시 저장 과실 (Fruit provisionally preserved)",
    "0813": "건조 과실 (Fruit, dried)",
    "0814": "감귤류·멜론 껍질 (Peel of citrus fruit or melons)",
    "0901": "커피 (Coffee)",
    "0902": "차 (Tea)",
    "0903": "마테 (Maté)",
    "0904": "후추·파프리카 (Pepper, dried/crushed capsicum)",
    "0905": "바닐라 (Vanilla)",
    "0906": "계피·계피나무 꽃 (Cinnamon and cinnamon-tree flowers)",
    "0907": "정향 (Cloves)",
    "0908": "육두구·메이스·카다몬 (Nutmeg, mace, cardamoms)",
    "0909": "아니스·팔각회향·회향·고수·쿠민·캐러웨이 씨 (Anise, badian, fennel, coriander, cumin seeds)",
    "0910": "생강·사프란·심황·기타 향신료 (Ginger, saffron, turmeric, other spices)",
    "1001": "밀·메슬린 (Wheat and meslin)",
    "1002": "호밀 (Rye)",
    "1003": "보리 (Barley)",
    "1004": "귀리 (Oats)",
    "1005": "옥수수 (Maize / Corn)",
    "1006": "쌀 (Rice)",
    "1007": "수수 (Grain sorghum)",
    "1008": "메밀·기장·카나리아새 먹이용 씨앗·기타 곡물 (Buckwheat, millet, canary seed, other cereals)",
    "1101": "밀가루·메슬린 가루 (Wheat or meslin flour)",
    "1102": "곡물 가루 (Cereal flours other than wheat or meslin)",
    "1103": "곡물 그로트·밀·펠릿 (Cereal groats, meal and pellets)",
    "1104": "가공 곡물 (Cereal grains otherwise worked)",
    "1105": "감자 가루·분말·플레이크·과립 (Flour, powder, flakes of potatoes)",
    "1106": "건조 두류·사고·뿌리 가루 (Flour, powder of dried leguminous vegetables, sago, roots)",
    "1107": "맥아 (Malt)",
    "1108": "전분류 (Starches, inulin)",
    "1109": "밀글루텐 (Wheat gluten)",
    "1201": "대두 (Soya beans)",
    "1202": "땅콩 (Ground-nuts)",
    "1203": "코프라 (Copra)",
    "1204": "아마 씨 (Linseed)",
    "1205": "유채·평지 씨 (Rape or colza seeds)",
    "1206": "해바라기 씨 (Sunflower seeds)",
    "1207": "기타 채유용 씨앗·결실 (Other oil seeds and oleaginous fruits)",
    "1208": "채유용 씨앗·결실 가루 (Flours and meals of oil seeds)",
    "1209": "파종용 씨앗·과실·포자 (Seeds, fruit and spores for sowing)",
    "1210": "홉의 솔방울 (Hop cones)",
    "1211": "식물·그 부분 (Plants and parts used in pharmacy/perfumery)",
    "1212": "당근·근대·사탕수수·해조류 (Locust beans, seaweeds, sugar beet, cane)",
    "1213": "곡물 짚·속대 (Cereal straw and husks)",
    "1214": "사탕무·건초·클로버·목초 (Swedes, mangolds, hay, clover, forage)",
    "1301": "락·천연검·수지 (Lac, natural gums, resins)",
    "1302": "식물성 수액·추출물 (Vegetable saps and extracts)",
    "1401": "식물성 편조물 재료 (Vegetable materials for plaiting)",
    "1404": "기타 식물성 생산품 (Vegetable products n.e.s.)",
    # 제3부: 동식물성 유지 (15장)
    "1501": "돼지지방·가금류 지방 (Pig fat, poultry fat)",
    "1502": "소·양·염소의 지방 (Fats of bovine, sheep or goat animals)",
    "1503": "라드스테아린·올레오오일·라드오일 (Lard stearin, lard oil, oleo-oil)",
    "1504": "어류·해양포유동물의 지방·기름 (Fats and oils of fish, marine mammals)",
    "1505": "양모지·지방성물질 (Wool grease and fatty substances)",
    "1506": "기타 동물성 지방·기름 (Other animal fats and oils)",
    "1507": "대두유 (Soya-bean oil)",
    "1508": "땅콩유 (Ground-nut oil)",
    "1509": "올리브유 (Olive oil)",
    "1510": "기타 올리브유 (Other oils obtained from olives)",
    "1511": "팜유 (Palm oil)",
    "1512": "해바라기씨유·잇꽃유·면실유 (Sunflower-seed, safflower, cotton-seed oil)",
    "1513": "야자유·팜핵유·바바수유 (Coconut oil, palm kernel oil, babassu oil)",
    "1514": "유채씨유·겨자씨유 (Rape, colza or mustard oil)",
    "1515": "기타 식물성 고정유 (Other fixed vegetable fats and oils)",
    "1516": "수소첨가 동식물성 유지 (Hydrogenated animal or vegetable fats)",
    "1517": "마가린·혼합유지 (Margarine, edible mixtures of fats)",
    "1518": "비식용 동식물성 유지 (Animal or vegetable fats, inedible)",
    "1520": "글리세롤 (Glycerol, crude)",
    "1521": "식물성 왁스·밀랍 (Vegetable waxes, beeswax)",
    "1522": "데그라스·유지 잔재물 (Degras, residues from fatty acids)",
    # 제4부: 식품공업 조제품 (16~24장)
    "1601": "소시지·유사 육제품 (Sausages and similar products of meat)",
    "1602": "기타 육류 조제품 (Other prepared or preserved meat, offal)",
    "1603": "육류·어류 엑스·육즙 (Extracts and juices of meat, fish)",
    "1604": "어류 조제품 (Prepared or preserved fish, caviar)",
    "1605": "갑각류·연체동물 조제품 (Crustaceans, molluscs, prepared/preserved)",
    "1701": "사탕수수당·사탕무당·정제당 (Cane or beet sugar, chemically pure sucrose)",
    "1702": "기타 당류 (Other sugars: lactose, maltose, glucose, fructose)",
    "1703": "당밀 (Molasses from extraction/refining of sugar)",
    "1704": "설탕과자 (Sugar confectionery)",
    "1801": "코코아두 (Cocoa beans, whole or broken)",
    "1802": "코코아 껍데기·껍질·폐기물 (Cocoa shells, husks, skins, waste)",
    "1803": "코코아 페이스트 (Cocoa paste)",
    "1804": "코코아 버터·지방·기름 (Cocoa butter, fat and oil)",
    "1805": "코코아 분말 (Cocoa powder, not sweetened)",
    "1806": "초콜릿·코코아 조제 식료품 (Chocolate and other cocoa food preparations)",
    "1901": "맥아 추출물·곡물 조제 식료품 (Malt extract, cereal food preparations)",
    "1902": "파스타·쿠스쿠스 (Pasta, couscous)",
    "1903": "타피오카 (Tapioca)",
    "1904": "팽화·볶은 곡물 조제품 (Prepared foods of cereals by puffing/roasting)",
    "1905": "빵·케이크·과자·비스킷 (Bread, pastry, cakes, biscuits, wafers)",
    "2001": "식초 조제 채소·과실·견과류 (Vegetables, fruit, nuts prepared with vinegar)",
    "2002": "토마토 조제품 (Tomatoes prepared or preserved)",
    "2003": "버섯·송로버섯 조제품 (Mushrooms and truffles, prepared/preserved)",
    "2004": "기타 냉동 채소 조제품 (Other vegetables prepared/preserved, frozen)",
    "2005": "기타 채소 조제품 (Other vegetables prepared/preserved, not frozen)",
    "2006": "당장 과실·견과류·껍질 (Fruit, nuts, preserved by sugar)",
    "2007": "잼·젤리·마멀레이드·퓌레 (Jams, jellies, marmalades, pastes, purées)",
    "2008": "기타 과실·견과류 조제품 (Fruit, nuts, otherwise prepared/preserved)",
    "2009": "과실주스·채소주스 (Fruit juices and vegetable juices)",
    "2101": "커피·차·마테 추출물 (Extracts of coffee, tea or maté)",
    "2102": "효모·기타 단세포 미생물·베이킹파우더 (Yeasts, other microorganisms, baking powder)",
    "2103": "소스·혼합 조미료·머스터드 (Sauces and preparations, mixed condiments, mustard)",
    "2104": "수프·부용·조제품 (Soups and broths and preparations)",
    "2105": "아이스크림 (Ice cream and other edible ice)",
    "2106": "기타 조제 식료품 (Food preparations n.e.s.)",
    "2201": "물·광천수·탄산수 (Waters, mineral waters, aerated waters)",
    "2202": "비알코올 음료 (Waters with added sugar; non-alcoholic beverages)",
    "2203": "맥주 (Beer made from malt)",
    "2204": "와인 (Wine of fresh grapes)",
    "2205": "버무스·기타 포도주 (Vermouth and other wine flavoured with plants)",
    "2206": "기타 발효 음료 (Other fermented beverages: cider, perry, mead)",
    "2207": "에틸알코올 (Ethyl alcohol, undenatured, ≥80% vol.)",
    "2208": "주류 (Spirits, liqueurs, other spirituous beverages)",
    "2209": "식초·대용 식초 (Vinegar and substitutes for vinegar)",
    "2301": "사료용 가루·밀·펠릿 (Flours, meals, pellets of meat/fish for animal feed)",
    "2302": "곡물·두류 겨·박·잔재물 (Bran, sharps and other residues of cereals)",
    "2303": "전분 제조 잔재물·사탕무 절육·양조 잔재물 (Residues from starch manufacture)",
    "2304": "대두박 (Oilcake of soya-bean)",
    "2305": "땅콩박 (Oilcake of ground-nuts)",
    "2306": "기타 식물성 유지박 (Oilcake of other vegetable fats)",
    "2307": "포도주 잔재물·주석 (Wine lees, argol)",
    "2308": "동물·식물성 사료용 재료 (Vegetable materials for animal feeding n.e.s.)",
    "2309": "동물 사료용 조제품 (Preparations for animal feeding)",
    "2401": "담배 잎 (Unmanufactured tobacco)",
    "2402": "궐련·엽권련·기타 담배 제품 (Cigars, cigarettes, smoking tobacco)",
    "2403": "기타 담배 제품·담배 대용물 (Other manufactured tobacco, tobacco substitutes)",
    # 제5부: 광물성 생산품 (25~27장) — 주요 품목
    "2501": "소금·염화나트륨 (Salt, pure sodium chloride)",
    "2601": "철광석·정광 (Iron ores and concentrates)",
    "2602": "망간광석·정광 (Manganese ores and concentrates)",
    "2603": "구리광석·정광 (Copper ores and concentrates)",
    "2604": "니켈광석·정광 (Nickel ores and concentrates)",
    "2606": "알루미늄광석·정광 (Aluminium ores and concentrates)",
    "2609": "주석광석·정광 (Tin ores and concentrates)",
    "2610": "크롬광석·정광 (Chromium ores and concentrates)",
    "2611": "텅스텐광석·정광 (Tungsten ores and concentrates)",
    "2614": "티타늄광석·정광 (Titanium ores and concentrates)",
    "2616": "귀금속광석·정광 (Precious metal ores and concentrates)",
    "2620": "재·잔재물 (Slag, ash, residues containing metals)",
    "2701": "석탄·연탄·코크스 (Coal, briquettes, ovoids from coal)",
    "2702": "갈탄 (Lignite)",
    "2703": "피트 (Peat)",
    "2704": "코크스·반성코크스 (Coke and semi-coke of coal, lignite, peat)",
    "2706": "콜타르·기타 광물성 타르 (Coal tar, other mineral tars)",
    "2709": "석유·역청유 (Petroleum oils and oils from bituminous minerals, crude)",
    "2710": "석유제품 (Petroleum oils, not crude)",
    "2711": "석유 가스·기타 가스상 탄화수소 (Petroleum gases and other gaseous hydrocarbons)",
    "2712": "석유 젤리·광물성 왁스 (Petroleum jelly, mineral waxes)",
    "2713": "석유 코크스·석유 역청 (Petroleum coke, petroleum bitumen)",
    "2714": "역청·아스팔트 (Bitumen and asphalt, natural)",
    # 주요 공산품 (84~85장 일부)
    "8471": "자동자료처리기계·컴퓨터 (Automatic data processing machines, computers)",
    "8517": "전화기·스마트폰·통신기기 (Telephone sets, smartphones, communication apparatus)",
    "8541": "반도체디바이스·LED (Semiconductor devices, LEDs)",
    "8542": "전자집적회로 (Electronic integrated circuits)",
    "8703": "승용자동차 (Motor cars and other vehicles for transport of persons)",
    "8704": "화물자동차 (Motor vehicles for transport of goods)",
    "8708": "자동차 부품·부속품 (Parts and accessories for motor vehicles)",
    "8802": "항공기·우주선 (Aircraft, spacecraft)",
    "9401": "의자류 (Seats)",
    "9403": "기타 가구 (Other furniture)",
}

# HS 6자리 소호 (농축수산물 섹션 I-IV 집중 + 주요 쇠고기 품목)
HS6_CODES = {
    # 쇠고기 (0201~0202)
    "020110": "쇠고기 냉장-도체·반도체 (Carcasses and half-carcasses, fresh/chilled)",
    "020120": "쇠고기 냉장-기타 뼈 있는 부분육 (Other cuts with bone in, fresh/chilled)",
    "020130": "쇠고기 냉장-뼈 없는 것 (Boneless, fresh/chilled)",
    "020210": "쇠고기 냉동-도체·반도체 (Carcasses and half-carcasses, frozen)",
    "020220": "쇠고기 냉동-기타 뼈 있는 부분육 (Other cuts with bone in, frozen)",
    "020230": "쇠고기 냉동-뼈 없는 것 (Boneless, frozen)",
    # 돼지고기 (0203)
    "020311": "돼지고기 냉장-도체·반도체 (Carcasses and half-carcasses, fresh/chilled)",
    "020312": "돼지고기 냉장-햄·어깨·부분육 (Hams, shoulders, fresh/chilled)",
    "020319": "돼지고기 냉장-기타 (Other, fresh/chilled)",
    "020321": "돼지고기 냉동-도체·반도체 (Carcasses and half-carcasses, frozen)",
    "020322": "돼지고기 냉동-햄·어깨·부분육 (Hams, shoulders, frozen)",
    "020329": "돼지고기 냉동-기타 (Other, frozen)",
    # 가금류 (0207)
    "020711": "닭 분할하지 않은 것 냉장 (Fowls of species Gallus domesticus, not cut, fresh/chilled)",
    "020712": "닭 분할하지 않은 것 냉동 (Fowls of species Gallus domesticus, not cut, frozen)",
    "020713": "닭 부분육 냉장 (Cuts and offal of fowls, fresh/chilled)",
    "020714": "닭 부분육 냉동 (Cuts and offal of fowls, frozen)",
    "020724": "칠면조 부분육 냉동 (Cuts and offal of turkeys, frozen)",
    "020727": "오리 부분육 냉동 (Cuts and offal of ducks, frozen)",
    # 어류 (0302~0305)
    "030211": "송어 신선·냉장 (Trout, fresh or chilled)",
    "030212": "연어 신선·냉장 (Salmonidae, fresh or chilled)",
    "030213": "태평양연어 신선·냉장 (Pacific salmon, fresh or chilled)",
    "030231": "날개다랑어 신선·냉장 (Albacore or longfinned tunas, fresh/chilled)",
    "030232": "황다랑어 신선·냉장 (Yellowfin tunas, fresh/chilled)",
    "030233": "눈다랑어 신선·냉장 (Bigeye tunas, fresh/chilled)",
    "030311": "태평양연어 냉동 (Pacific salmon, frozen)",
    "030312": "대서양연어·다뉴브강연어 냉동 (Atlantic salmon, Danube salmon, frozen)",
    "030331": "날개다랑어 냉동 (Albacore or longfinned tunas, frozen)",
    "030332": "황다랑어 냉동 (Yellowfin tunas, frozen)",
    "030333": "눈다랑어 냉동 (Bigeye tunas, frozen)",
    "030341": "청어 냉동 (Herrings, frozen)",
    "030342": "정어리·샤르디넬라·청어과 냉동 (Sardines, sardinella, brisling, sprats, frozen)",
    "030343": "고등어 냉동 (Mackerel, frozen)",
    "030344": "가다랑어·꽁치·기타 냉동 (Skipjack/stripe-bellied bonito, frozen)",
    "030345": "명태 냉동 (Alaska Pollack, frozen)",
    "030346": "대서양대구·그린란드대구 냉동 (Atlantic cod, Greenland cod, frozen)",
    "030361": "정어리 냉동 (Sardines, frozen)",
    "030362": "해덕 냉동 (Haddock, frozen)",
    "030363": "석대구 냉동 (Pacific cod, frozen)",
    "030364": "고등어 냉동-기타 (Mackerel, frozen, other)",
    "030389": "기타 어류 냉동 (Other fish, frozen)",
    # 갑각류 (0306)
    "030611": "왕새우·로브스터 냉동 (Rock lobster, sea crawfish, frozen)",
    "030612": "바닷가재 냉동 (Lobsters, frozen)",
    "030613": "대하·새우 냉동 (Shrimps and prawns, frozen)",
    "030614": "게 냉동 (Crabs, frozen)",
    "030616": "냉동 새우·대하 (Shrimps and prawns, frozen)",
    "030617": "냉동 게 (Crabs, frozen)",
    # 쌀 (1006)
    "100610": "벼 (Rice in the husk / paddy or rough rice)",
    "100620": "현미 (Husked (brown) rice)",
    "100630": "반정백미·정백미 (Semi-milled or wholly milled rice)",
    "100640": "쇄미 (Broken rice)",
    # 밀 (1001)
    "100111": "듀럼밀 씨앗용 (Durum wheat, seed)",
    "100119": "듀럼밀 기타 (Durum wheat, other)",
    "100191": "기타 밀 씨앗용 (Other wheat and meslin, seed)",
    "100199": "기타 밀 기타 (Other wheat and meslin, other)",
    # 옥수수 (1005)
    "100510": "옥수수 씨앗용 (Maize, seed)",
    "100590": "옥수수 기타 (Maize, other)",
    # 대두 (1201)
    "120110": "대두 씨앗용 (Soya beans, seed)",
    "120190": "대두 기타 (Soya beans, other)",
    # 유채씨 (1205)
    "120510": "유채씨 저에루신산 (Low erucic acid rape/colza seeds)",
    "120590": "기타 유채씨 (Other rape or colza seeds)",
    # 팜유 (1511)
    "151110": "팜유 조유 (Palm oil, crude)",
    "151190": "팜유 기타 (Palm oil, other)",
    # 대두유 (1507)
    "150710": "대두유 조유 (Soya-bean oil, crude)",
    "150790": "대두유 기타 (Soya-bean oil, other)",
    # 설탕 (1701)
    "170111": "사탕수수당 조당 (Cane sugar, raw, solid)",
    "170112": "사탕무당 조당 (Beet sugar, raw, solid)",
    "170191": "사탕수수당·사탕무당 정제당 (Refined sugar, solid)",
    "170199": "기타 당류 (Other sugars)",
    # 커피 (0901)
    "090111": "생두 로스팅 안 한 것 (Coffee, not roasted, not decaffeinated)",
    "090112": "생두 디카페인 (Coffee, not roasted, decaffeinated)",
    "090121": "원두 로스팅된 것 (Coffee, roasted, not decaffeinated)",
    "090122": "원두 디카페인 (Coffee, roasted, decaffeinated)",
    # 면화 (5201~5203)
    "520100": "조면 (Cotton, not carded or combed)",
    "520210": "면사 폐설물 (Cotton yarn waste)",
    "520300": "소면·정소면 (Cotton, carded or combed)",
    # 기타 주요 농산물
    "151311": "코코넛유 조유 (Coconut (copra) oil, crude)",
    "151319": "코코넛유 기타 (Coconut (copra) oil, other)",
    "080111": "코코넛 신선 (Coconuts, fresh)",
    "080132": "코코넛 건조 (Coconuts, dried)",
    "080211": "아몬드 껍데기 있는 것 (Almonds, in shell)",
    "080212": "아몬드 껍데기 없는 것 (Almonds, shelled)",
    "080231": "호두 껍데기 있는 것 (Walnuts, in shell)",
    "080232": "호두 껍데기 없는 것 (Walnuts, shelled)",
    "080510": "오렌지 (Oranges)",
    "080520": "만다린·클레멘타인 (Mandarins, clementines, wilkings)",
    "080540": "자몽·포멜로 (Grapefruit)",
    "080550": "레몬·라임 (Lemons and limes)",
    "080590": "기타 감귤류 (Other citrus fruit)",
    "080610": "신선 포도 (Grapes, fresh)",
    "080620": "건포도 (Grapes, dried / raisins)",
    "080810": "사과 (Apples)",
    "080820": "배·마르멜로 (Pears and quinces)",
    "080830": "배 (Pears)",
    "080840": "마르멜로 (Quinces)",
    "070200": "신선·냉장 토마토 (Tomatoes, fresh or chilled)",
    "070310": "양파·쪽파 (Onions and shallots)",
    "070320": "마늘 (Garlic)",
    "070700": "오이·거킨 (Cucumbers and gherkins)",
    "071010": "감자 냉동 (Potatoes, frozen)",
    "071021": "완두 냉동 (Peas, frozen)",
    "071022": "콩 냉동 (Beans, frozen)",
    "071080": "기타 채소 냉동 (Other vegetables, frozen)",
    "090111": "커피 생두 (Coffee, not roasted)",
    "100110": "듀럼밀 (Durum wheat)",
    "100300": "보리 (Barley)",
    "100400": "귀리 (Oats)",
    "100700": "수수 (Grain sorghum)",
    "110100": "밀가루 (Wheat or meslin flour)",
    "110710": "맥아 볶지 않은 것 (Malt, not roasted)",
    "110720": "맥아 볶은 것 (Malt, roasted)",
    "120100": "대두 (Soya beans)",
    "120600": "해바라기씨 (Sunflower seeds)",
    "170310": "사탕수수당밀 (Cane molasses)",
    "170390": "기타 당밀 (Other molasses)",
    "230400": "대두박 (Oilcake and other solid residues of soya-bean)",
    "230610": "면실박 (Oilcake of cotton seeds)",
    "230630": "해바라기씨박 (Oilcake of sunflower seeds)",
    "230641": "유채씨박 저에루신산 (Oilcake of low erucic acid rape/colza seeds)",
    "230649": "유채씨박 기타 (Oilcake of other rape/colza seeds)",
    "230690": "기타 식물성 유지박 (Other oilcake and solid residues)",
    "230910": "개·고양이 사료 (Dog or cat food, retail)",
    "230990": "기타 동물 사료 (Other preparations for animal feeding)",
}
